PUBLIC_BASE_URL=...
PUBLIC_LINK_SECRET=...
PIPE_API_KEY=...
PIPE_GRAPHQL_ENDPOINT=https://api.pipefy.com/graphql
D4SIGN_CRYPT_KEY=...
D4SIGN_TOKEN=...
TEMPLATE_UUID_CONTRATO=...

# conectores/tabelas
FIELD_ID_CONNECT_MARCA_NOME=marcas_1
FIELD_ID_CONNECT_CLASSE=marcas_2
# (opcional) se tiver conector direto:
# FIELD_ID_CONNECT_CLASSES=classes_inpi
CLASSES_TABLE_ID=306521337

# campo do card para gravar o link
PIPEFY_FIELD_LINK_CONTRATO=d4_contrato

# cofre(s)
COFRE_UUID_EDNA=...
# ...demais cofres
# DEFAULT_COFRE_UUID=... (opcional)
